---
title: "Self-Assessment Instructions"
output:
  html_document:
    theme: cosmo
    highlight: zenburn
    css: "note-style.css"
---

**Due Date**: 03 December 2021 by 5pm

## Instructions

The course syllabus describes the self-assessment as follows:

> A reflection recording one's effort and engagement during the semester is due on
> the last day of class. A grade will be given out of 95 points.

The self-assessment consists of your responses to five questions. Each of these
should take the form of a paragraph or two. You should be able to answer these 
in about a page, with a strict limit of two pages total. The questions to respond
to are:

1. What did you hope to get out of the class? Have you met these goals?
2. Briefly explain how you prepared for the classes and exams.
3. Which topic was your favorite? Why?
4. If a friend asked you to describe the most significant thing you learned
this semester, what would you say?
5. How might you be able to use the skills in this course in future work, such
as a research project, other courses, graduate school, or a career. Try to be
specific.

You can submit your assessment as either a pdf file or a docx file; the
file should be named `selfassessment_first_last.docx` or
`selfassessment_first_last.pdf` with your first and list names filled in.
You may download a
[template document file](https://github.com/statsmaths/dsst289-f21/raw/main/self_assess/selfassessment_first_last.docx)
to use. Please upload your responses to Box before the due date and time
listed above.
