---
title: "purrr"
output:
  html_document:
    theme: cosmo
    highlight: zenburn
    css: "note-style.css"
---

```{r, include=FALSE, message=FALSE}
source("start.R")

food <- read_csv(file.path("data", "food.csv"))
food_prices <- read_csv(file.path("data", "food_prices.csv"))

Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 10000)
```

```{r}
base_url <- "https://en.wikipedia.org/w/api.php"
options <- "?action=query&format=json&prop=pageviews&titles="
url <- stri_paste(base_url, options, "apple")

json_text <- read_lines(url)
obj <- parse_json(json_text)
```

```{r}
obj$query$pages$`18978754`$pageid
obj$query$pages$`18978754`$ns
obj$query$pages$`18978754`$title
```

```{r}
pv <- obj$query$pages$`18978754`$pageviews

df <- tibble(
  pageid = obj$query$pages$`18978754`$pageid,
  ns = obj$query$pages$`18978754`$ns,
  title = obj$query$pages$`18978754`$title,
  date = ymd(names(pv)),
  pageviews = map_int(pv, function(v) v)
)

df %>%
  ggplot(aes(date, pageviews)) +
    geom_line()
```

## Weather



```{r}
lat <- 37.533333 
lon <- -77.466667 

points_url <- sprintf("https://api.weather.gov/points/%f,%f", lat, lon)
points_obj <- parse_json(read_lines(points_url))
grid_x <- points_obj$properties$gridX
grid_y <- points_obj$properties$gridY
```


```{r}
base_url <- "https://api.weather.gov/gridpoints/TOP/%d,%d/forecast?units=si"
forecast_url <- sprintf(base_url, grid_x, grid_y)
forecast_obj <- parse_json(read_lines(forecast_url))
```

```{r}
periods <- forecast_obj$properties$periods
length(periods)
```

```{r}
periods[[1]]
```



```{r}
obj <- forecast_obj$properties$periods
forecast <- tibble(
 name = map_chr(obj, ~ ..1$name ),
 start_time = ymd_hms(map_chr(obj, ~ ..1$startTime )),
 endTime = ymd_hms(map_chr(obj, ~ ..1$endTime )),
 temperature = map_dbl(obj, ~ ..1$temperature ),
 day_time = map_lgl(obj, ~ ..1$isDaytime ),
 wind_speed = map_chr(obj, ~ ..1$windSpeed ),
 wind_direction = map_chr(obj, ~ ..1$windDirection ),
 short_forecast = map_chr(obj, ~ ..1$shortForecast )
)

forecast
```

```{r}
forecast %>%
  mutate(start_time = with_tz(start_time, "America/New_York")) %>%
  mutate(day_of_week = wday(start_time, label = TRUE)) %>%
  ggplot(aes(start_time, temperature)) +
    geom_point(aes(color = day_time), size = 4, show.legend = FALSE) +
    geom_line(aes(color = day_time), linetype = "dashed", show.legend = FALSE) +
    geom_text(aes(y = temperature + 1, label = temperature, color = day_time), show.legend = FALSE) +
    scale_color_viridis_d(begin = 0.3, end = 0.75) +
    theme_sm() +
    scale_x_datetime(date_breaks = "1 day", date_labels = "%d %b")
```


```{r}
forecast <- map_df(periods, function(v) {
  df <- tibble(
    name = v$name,
    start_time = ymd_hms(v$startTime),
    end_time = ymd_hms(v$endTime),
    temperature = v$temperature,
    wind_speed = v$windSpeed,
    wind_direction = v$windDirection,
    short_forecase = v$shortForecast  
  )
  return(df)
})
forecast
```

### Hourly

```{r}
base_url <- "https://api.weather.gov/gridpoints/TOP/%d,%d/forecast/hourly?units=si"
forecast_url <- sprintf(base_url, grid_x, grid_y)
forecast_obj <- parse_json(read_lines(forecast_url))
```

```{r}
periods <- forecast_obj$properties$periods
length(periods)
```

```{r}
forecast <- map_df(periods, function(v) {
  df <- tibble(
    start_time = ymd_hms(v$startTime),
    end_time = ymd_hms(v$endTime),
    temperature = v$temperature,
    wind_speed = v$windSpeed,
    wind_direction = v$windDirection,
    short_forecase = v$shortForecast  
  )
  return(df)
})
forecast
```

```{r}
obj <- forecast_obj$properties$periods
forecast <- tibble(
 name = map_chr(obj, ~ ..1$name ),
 start_time = ymd_hms(map_chr(obj, ~ ..1$startTime )),
 endTime = ymd_hms(map_chr(obj, ~ ..1$endTime )),
 temperature = map_dbl(obj, ~ ..1$temperature ),
 wind_speed = map_chr(obj, ~ ..1$windSpeed ),
 wind_direction = map_chr(obj, ~ ..1$windDirection ),
 short_forecast = map_chr(obj, ~ ..1$shortForecast )
)
```


```{r}
forecast %>%
  ggplot(aes(start_time, temperature)) +
    geom_line(aes(color = factor(day(start_time))), size = 2, show.legend = FALSE)
```

```{r}
forecast %>%
  mutate(start_time = with_tz(start_time, "America/New_York")) %>%
  mutate(day_of_week = wday(start_time, label = TRUE)) %>%
  ggplot(aes(start_time, temperature)) +
    geom_line(aes(color = day_of_week), size = 2)
```


## Crypto

```{r}
crypto_url <- "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=usd&days=30"
crypto_obj <- parse_json(read_lines(crypto_url))
```

```{r}
names(crypto_obj)
```


```{r}
crypto_obj$prices[[1]]
```


```{r}
time_ms <- map_dbl(crypto_obj$prices, function(v) {
  v[[1]]
})
price <- map_dbl(crypto_obj$prices, function(v) {
  v[[2]]
})
market_cap <- map_dbl(crypto_obj$market_caps, function(v) {
  v[[2]]
})
volume <- map_dbl(crypto_obj$total_volumes, function(v) {
  v[[2]]
})


df <- tibble(
  time = as_datetime(time_ms / 1000),
  price = price,
  market_cap = market_cap,
  volume
)
df
```

```{r}
df %>%
  ggplot(aes(time, price)) +
    geom_line()
```

## Hacker News

```{r}
hn_top_url <- "https://hacker-news.firebaseio.com/v0/topstories.json"
hn_top_obj <- parse_json(read_lines(hn_top_url))
hn_top_obj <- as.integer(hn_top_obj)
```

```{r}
hn_id_url <- "https://hacker-news.firebaseio.com/v0/item/%d.json"
id <- hn_top_obj[1]

hn_obj <- parse_json(read_lines(sprintf(hn_id_url, id)))
names(hn_obj)
```

```{r}
kid_ids <- as.integer(hn_obj$kids)
```

```{r}
hn_kid_obj <- parse_json(read_lines(sprintf(hn_id_url, kid_ids[1])))
hn_kid_obj
```

```{r}
hn_user_url <- "https://hacker-news.firebaseio.com/v0/user/%s.json"

user <- hn_obj$by
hn_obj <- parse_json(read_lines(sprintf(hn_user_url, user)))
names(hn_obj)
```

```{r}
hn_obj$about
```


```{r}
df_hn <- map_df(head(hn_top_obj), function(v) {
  obj <- parse_json(read_lines(sprintf(hn_id_url, v)))

  df <- tibble(
    by = obj$by,
    type = obj$type,
    title = obj$title,
    score = obj$score,
    time = obj$time,
    kids = length(obj$kids),
    descendants = obj$descendants,
    url = obj$url
  )
  return(df)
})
df_hn
```

## XKCD

```{r}
xkcd_url <- "https://xkcd.com/%d/info.0.json"
xkcd_obj <- parse_json(read_lines(sprintf(xkcd_url, 301)))
xkcd_obj
```

```{r}
cat(xkcd_obj$transcript)
```

## Census

```{r}
"https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address=8+N+Rowland,Richmond,VA&benchmark=2020&format=json"
```




