---
title: "Notebook 23 -- Solutions"
output:
  html_document:
    theme: cosmo
    highlight: zenburn
    css: "note-style.css"
---

## Getting Started

Before running this notebook, select "Session > Restart R and Clear Output" in
the menu above to start a new R session. This will clear any old data sets and
give us a blank slate to start with.

After starting a new session, run the following code chunk to load the
libraries and data that we will be working with today.

```{r, include=FALSE, message=FALSE}
source("start.R")
source("cache.R")

sm_centroid <- function(data) {
  suppressWarnings({ z <- st_coordinates(st_centroid(data)) })
  return(tibble(lon = z[,1], lat = z[,2]))
}
spatial_join <- function(...) {
  return(st_as_sf(as_tibble(st_join(...))))
}
klog_readfile <- function(input) {
  dt <- readr::read_csv(input, col_types = "dcccllllldd", na = character())
  dt$key[dt$key_code == "Space"] <- " "
  dt$key[dt$key_code == "Enter"] <- "\n"
  return(dt)
}
```

## Keylogs

```{r}
kl <- klog_readfile("data/keylogs-1636337989526.csv")
kl
```

```{r}
kl %>%
  filter(type == "down") %>%
  filter(stri_length(key) == 1) %>%
  summarize(key = paste(key, collapse = "")) %>%
  magrittr::use_series(key) %>%
  cat()
```

```{r}
kl %>%
  filter(type == "down") %>%
  mutate(tdiff = lead(time, n = 1) - time) %>%
  filter(!is.na(tdiff)) %>%
  summarize(median(tdiff))
```

```{r}
kl %>%
  filter(type == "down") %>%
  mutate(tdiff = lead(time, n = 1) - time) %>%
  filter(tdiff < 400) %>%
  ggplot(aes(tdiff)) +
    geom_histogram(bins = 20, color = "black", fill = "white")
```

```{r}
kl %>%
  filter(type == "down") %>%
  mutate(tdiff = lead(time, n = 1) - time) %>%
  filter(!is.na(tdiff)) %>%
  group_by(key) %>%
  summarize(med = median(tdiff)) %>%
  arrange(desc(med))
```

```{r}
kl %>%
  filter(type %in% c("up", "down")) %>%
  group_by(key) %>%
  mutate(tdiff = lead(time, n = 1) - time) %>%
  filter(type == "down") %>%
  filter(!is.na(tdiff)) %>%
  ungroup() %>%
  summarize(med = median(tdiff))
```

```{r}
kl %>%
  filter(type %in% c("up", "down")) %>%
  group_by(key_code) %>%
  mutate(tdiff = lead(time, n = 1) - time) %>%
  filter(type == "down") %>%
  filter(!is.na(tdiff)) %>%
  group_by(key) %>%
  summarize(med = median(tdiff)) %>%
  arrange(desc(med))
```


```{r}
kl %>%
  filter(type == "down") %>%
  filter(key_code == "Space") %>%
  mutate(tdiff = lead(time, n = 1) - time) %>%
  filter(!is.na(tdiff)) %>%
  summarize(med = median(tdiff))
```

```{r}
kl %>%
  filter(type == "down") %>%
  mutate(id = seq_along(type)) %>%
  filter(key_code == "Space") %>%
  mutate(tdiff = lead(time, n = 1) - time) %>%
  mutate(nkey = lead(id, n = 1) - id) %>%
  filter(!is.na(tdiff)) %>%
  ggplot(aes(tdiff, nkey)) +
    geom_point()
```

```{r}
kl %>%
  filter(type == "down") %>%
  mutate(tdiff = lead(time, n = 1) - time) %>%
  mutate(key_lead = lead(key, n = 1)) %>%
  filter(key == "t", key_lead == "h") %>%
  summarize(n = n(), med = median(tdiff))
```

```{r}
kl %>%
  filter(type == "down") %>%
  mutate(tdiff = lead(time, n = 1) - time) %>%
  mutate(key_lead = lead(key, n = 1)) %>%
  filter(key == key_lead) %>%
  summarize(n = n(), med = median(tdiff))
```






