---
title: "Recreating Hans Roslin I"
output:
  html_document:
    theme: cosmo
    highlight: zenburn
    css: "note-style.css"
---

```{r, include=FALSE, message=FALSE}
library(tidyverse)
library(ggrepel)
library(smodels)
library(gapminder)

theme_set(theme_minimal())
options(pillar.min_character_chars = 15)
options(readr.show_col_types = FALSE)
options(width = 85L)
options(ggrepel.max.overlaps = Inf)
```

Let's create and load the data (we will see more about these functions for
next class):

```{r}
hans <- gapminder::gapminder %>%
  rename(life_exp = lifeExp, gdp = gdpPercap) %>%
  filter(year == 2007) %>%
  mutate(pop = pop / 1000000)

continent_colors <- gapminder::continent_colors
```

And now we'll look at the data:

```{r}
hans
```

Can we recreate the 'basic' plot from the video?

```{r}
hans %>%
  ggplot(aes(gdp, life_exp)) +
    geom_point(aes(color = continent, size = pop), alpha = 0.7) +
    scale_x_log10()
```

Now, let's try to get the scales even better:

```{r}
hans %>%
  ggplot(aes(gdp, life_exp)) +
    geom_point(aes(color = continent, size = pop), alpha = 0.7) +
    scale_x_log10(breaks = c(400, 4000, 40000)) +
    scale_y_continuous(breaks = c(25, 50, 75), limits = c(25, NA)) +
    scale_color_manual(values = continent_colors)
```

And finally, maybe some extra labels using the `labs` function?

```{r}
hans %>%
  ggplot(aes(gdp, life_exp)) +
    geom_point(aes(color = continent, size = pop), alpha = 0.7) +
    scale_x_log10(breaks = c(400, 4000, 40000)) +
    scale_y_continuous(breaks = c(25, 50, 75), limits = c(25, NA)) +
    scale_color_manual(values = continent_colors) +
    labs(
      x = "GDP per Person",
      y = "Life Expectancy",
      color = "Continent",
      size = "Population"
    )
```
